name: Schedule Crawler
on:
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
  GITHUB_REPOSITORY: "GNU-moa/gnumoa-crawler"
  FIREBASE_ADMIN_SDK: ${{ secrets.FIREBASE_ADMIN_SDK }}
jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x # Python 버전 선택
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run crawler
      run: python main.py # 크롤링을 실행하는 스크립트 파일의 이름
      
